### ISSUE TITLE
Unable to locate files

### ISSUE THREAD

**Issue by ghost** [marcottelab/super.complex#1]
Upon executing the provided bash script, getting the below errors. Kindly help

`artitioning graph nodes across compute nodes...
Growing communities...
Traceback (most recent call last):
  File "main4_sample.py", line 148, in <module>
    main()
  File "main4_sample.py", line 121, in main
    with open(seed_nodes_F, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'yeast/all_nodes_known_comp_n_pts_1/res_seed_nodes0'
Merging very similar communities...
Traceback (most recent call last):
  File "main5_postprocess.py", line 187, in <module>
    main()
  File "main5_postprocess.py", line 157, in main
    with open(out_comp_nm_sample + "_pred_comp_list" + str(i), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'yeast/results_conn_tapcliques/res_pred_comp_list0'
Comparing predicted and known communities...
Traceback (most recent call last):
  File "main6_eval.py", line 307, in <module>
    main()
  File "main6_eval.py", line 145, in main
    with open(inputs['dir_nm'] + inputs["out_comp_nm"] + '_pred.out', "r") as fn:
FileNotFoundError: [Errno 2] No such file or directory: 'yeast/results_conn_tapcliques/res_pred.out'
`

**Comment by meghanapalukuri** [comment]
The missing file res_seed_nodes0 should be constructed by the previous step
in the example bash script provided in the README:

echo Partitioning graph nodes across compute nodes...
python3 main3_partition_search_seeds.py --input_file_name $input_file_name
--out_dir_name $out_dir_name_meth --search_method $meth

Please check and debug accordingly.
